### ISSUE TITLE
Не работает с PhpStorm 8

### ISSUE THREAD

**Issue by antyblin** [gobozov/eazestorm#8]
При запуске с PhpStorm 8 плагин падает.

Error message:
com.intellij.openapi.ui.popup.ComponentPopupBuilder.setForceHeavyweight(Z)Lcom/intellij/openapi/ui/popup/ComponentPopupBuilder;
java.lang.NoSuchMethodError: com.intellij.openapi.ui.popup.ComponentPopupBuilder.setForceHeavyweight(Z)Lcom/intellij/openapi/ui/popup/ComponentPopupBuilder;
	at ru.eaze.MyPopupBase.showTextFieldPanel(MyPopupBase.java:707)
	at ru.eaze.MyPopupBase.initUI(MyPopupBase.java:554)
	at ru.eaze.MyPopup.initUI(MyPopup.java:49)
	at ru.eaze.MyPopupBase.invoke(MyPopupBase.java:203)
	at ru.eaze.action.JumpToEazeAction.showNavigationPopup(JumpToEazeAction.java:72)
	at ru.eaze.action.JumpToEazeAction.actionPerformed(JumpToEazeAction.java:56)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:564)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:611)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:463)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:206)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:518)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by antyblin** [comment]
Исправлено в форке.
https://github.com/gobozov/eazestorm/pull/9
